### ISSUE TITLE
KeyError: 'goog:chromeOptions'

### ISSUE THREAD

**Issue by WittmannF** [spinlud/py-linkedin-jobs-scraper#14]
I am running the sample code that has been provided, and I am getting the following error:
```
INFO:li:scraper:('Using strategy AnonymousStrategy',)
INFO:li:scraper:('Starting new query', "Query(query= options=QueryOptions(limit=27 locations=['Worldwide'] optimize=True))")
ERROR:li:scraper:('[][Worldwide]', KeyError('goog:chromeOptions'))
Traceback (most recent call last):
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/linkedin_scraper.py", line 184, in __run
    websocket_debugger_url = get_websocket_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 115, in get_websocket_debugger_url
    chrome_debugger_url = get_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 103, in get_debugger_url
    chrome_debugger_url = f"http://{driver.capabilities['goog:chromeOptions']['debuggerAddress']}"
KeyError: 'goog:chromeOptions'
[ON_ERROR] 'goog:chromeOptions'
Traceback (most recent call last):
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/linkedin_scraper.py", line 184, in __run
    websocket_debugger_url = get_websocket_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 115, in get_websocket_debugger_url
    chrome_debugger_url = get_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 103, in get_debugger_url
    chrome_debugger_url = f"http://{driver.capabilities['goog:chromeOptions']['debuggerAddress']}"
KeyError: 'goog:chromeOptions'

[ON_END]
INFO:li:scraper:('Starting new query', "Query(query=Engineer options=QueryOptions(limit=5 locations=['United States'] filters=QueryFilters(company_jobs_url=https://www.linkedin.com/jobs/search/?f_C=1441%2C17876832%2C791962%2C2374003%2C18950635%2C16140%2C10440912&geoId=92000000 relevance=RelevanceFilters.RECENT time=TimeFilters.MONTH type=[<TypeFilters.FULL_TIME: 'F'>, <TypeFilters.INTERNSHIP: 'I'>]) optimize=False))")
ERROR:li:scraper:('[Engineer][United States]', KeyError('goog:chromeOptions'))
Traceback (most recent call last):
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/linkedin_scraper.py", line 184, in __run
    websocket_debugger_url = get_websocket_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 115, in get_websocket_debugger_url
    chrome_debugger_url = get_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 103, in get_debugger_url
    chrome_debugger_url = f"http://{driver.capabilities['goog:chromeOptions']['debuggerAddress']}"
KeyError: 'goog:chromeOptions'
[ON_ERROR] 'goog:chromeOptions'
Traceback (most recent call last):
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/linkedin_scraper.py", line 184, in __run
    websocket_debugger_url = get_websocket_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 115, in get_websocket_debugger_url
    chrome_debugger_url = get_debugger_url(driver)
  File "/Users/wittmann/anaconda/envs/p3/lib/python3.9/site-packages/linkedin_jobs_scraper/utils/chrome_driver.py", line 103, in get_debugger_url
    chrome_debugger_url = f"http://{driver.capabilities['goog:chromeOptions']['debuggerAddress']}"
KeyError: 'goog:chromeOptions'

[ON_END]

```

**Comment by spinlud** [comment]
Hi there, on which OS?

**Comment by WittmannF** [comment]
Hey @spinlud, I'm using MacOS

**Comment by spinlud** [comment]
Weird, I am on Mac too. Are you using latest Chrome and chromedriver stable versions?

Currently I am testing on:
* MacOS 10.15.7
* Chrome: 90.0.4430.212 (Official Build) (x86_64)
* chromedriver: 90.0.4430.24

**Comment by spinlud** [comment]
Closing. This targets `AnonymousStrategy` and the old driver-setup path, both removed in 6.0.0, so that code path no longer exists. Please use the latest version.
