### ISSUE TITLE
ValueError: Timeout value connect was <object object at 0x0000018E9C838840>

### ISSUE THREAD

**Issue by pbhusari** [spinlud/py-linkedin-jobs-scraper#60]
I get the following issue with chromedriver version  111.0.5563.64 on an authenticated session using the example script:

```
[ON_ERROR] Timeout value connect was <object object at 0x000002731D478840>, but it must be an int, float or None.
Traceback (most recent call last):
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\linkedin_jobs_scraper\linkedin_scraper.py", line 165, in __run
    driver = build_driver(
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\linkedin_jobs_scraper\utils\chrome_driver.py", line 91, in build_driver
    driver = webdriver.Chrome(**kwargs)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\poolmanager.py", line 422, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\poolmanager.py", line 303, in connection_from_host
    return self.connection_from_context(request_context)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\poolmanager.py", line 328, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\poolmanager.py", line 351, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\poolmanager.py", line 265, in _new_pool
    return pool_cls(host, port, **request_context)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\connectionpool.py", line 196, in __init__
    timeout = Timeout.from_float(timeout)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\util\timeout.py", line 190, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\util\timeout.py", line 119, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "C:\Users\pbhusari\PycharmProjects\pythonProject\venv\lib\site-packages\urllib3\util\timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x000002731D478840>, but it must be an int, float or None.

[ON_END]

Process finished with exit code 0

```

**Comment by pbhusari** [comment]
Issue persists when using version `111.0.5563.64`

**Comment by pbhusari** [comment]
imported version of urllib < 2.0
