### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by fnagy** [spinlud/py-linkedin-jobs-scraper#90]
Hello,

I was running the script today after having launched it several times with success in the past days. I get the error below. How can i fix it?

```
INFO:li:scraper:('[Data science team lead][European Economic Area]', 'Setting authentication cookie')
INFO:li:scraper:('[Data science team lead][European Economic Area]', 'Opening https://www.linkedin.com/jobs/search?keywords=Data+science+team+lead&location=European+Economic+Area&sortBy=DD&f_TPR=r86400&f_JT=C%2CF&f_WT=2%2C3&start=0')
INFO:li:scraper:('[Data science team lead][European Economic Area]', 'Session is valid')
WARNING:li:scraper:('[Data science team lead][European Economic Area][1]', 'Session is no longer valid, this may cause the scraper to fail')
ERROR:li:scraper:('[Data science team lead][European Economic Area][1]', JavascriptException(), 'Traceback (most recent call last):\n  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/linkedin_jobs_scraper/strategies/authenticated_strategy.py", line 383, in run\n    driver.execute_script(\n  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 414, in execute_script\n    return self.execute(command, {"script": script, "args": converted_args})["value"]\n  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute\n    self.error_handler.check_response(response)\n  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\nseleniu...
Traceback (most recent call last):
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/linkedin_jobs_scraper/strategies/authenticated_strategy.py", line 383, in run
    driver.execute_script(
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 414, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'querySelector')
  (Session info: chrome=127.0.6533.89)
Stacktrace:
0   chromedriver                        0x00000001051d9088 cxxbridge1$str$ptr + 1887276
1   chromedriver                        0x00000001051d1764 cxxbridge1$str$ptr + 1856264
2   chromedriver                        0x0000000104de082c cxxbridge1$string$len + 88524
3   chromedriver                        0x0000000104de57f8 cxxbridge1$string$len + 108952
4   chromedriver                        0x0000000104de72d4 cxxbridge1$string$len + 115828
5   chromedriver                        0x0000000104e5cfc4 cxxbridge1$string$len + 598372
6   chromedriver                        0x0000000104e5c48c cxxbridge1$string$len + 595500
7   chromedriver                        0x0000000104e19474 cxxbridge1$string$len + 321044
8   chromedriver                        0x0000000104e1a0e4 cxxbridge1$string$len + 324228
9   chromedriver                        0x00000001051a0a6c cxxbridge1$str$ptr + 1656336
10  chromedriver                        0x00000001051a54c8 cxxbridge1$str$ptr + 1675372
11  chromedriver                        0x0000000105186950 cxxbridge1$str$ptr + 1549556
12  chromedriver                        0x00000001051a5c78 cxxbridge1$str$ptr + 1677340
13  chromedriver                        0x0000000105178660 cxxbridge1$str$ptr + 1491460
14  chromedriver                        0x00000001051c2ac0 cxxbridge1$str$ptr + 1795684
15  chromedriver                        0x00000001051c2c3c cxxbridge1$str$ptr + 1796064
16  chromedriver                        0x00000001051d1398 cxxbridge1$str$ptr + 1855292
17  libsystem_pthread.dylib             0x000000019b746f94 _pthread_start + 136
18  libsystem_pthread.dylib             0x000000019b741d34 thread_start + 8

INFO:li:scraper:('[Data science team lead][European Economic Area][1]', 'Failed to process')
INFO:li:scraper:('[Data science team lead][European Economic Area][2]', 'Failed to process')
ERROR:li:scraper:('[Data science team lead][European Economic Area]', NoSuchWindowException())
Traceback (most recent call last):
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/linkedin_jobs_scraper/strategies/authenticated_strategy.py", line 383, in run
    driver.execute_script(
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 414, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/Users/federico/.pyenv/versions/3.10.0/envs/li_scraper2/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
```

**Comment by spinlud** [comment]
Try to update to latest version and generate a new session cookie
